# Generated by Django 4.2.7 on 2023-11-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_user', models.CharField(max_length=255)),
                ('last_name_user', models.CharField(max_length=255)),
                ('login_user', models.CharField(max_length=255)),
                ('password_user', models.CharField(max_length=255)),
                ('age_user', models.PositiveIntegerField()),
                ('about_user', models.TextField()),
                ('image_user', models.ImageField(upload_to='')),
                ('hobby_user', models.CharField(max_length=255)),
                ('music_user', models.CharField(max_length=255)),
                ('films_user', models.CharField(max_length=255)),
            ],
        ),
    ]
