# Generated by Django 4.2.7 on 2023-11-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_human_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='image_user',
        ),
    ]
