# Generated by Django 4.2.7 on 2023-11-18 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_human_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='slug',
        ),
    ]
